In [1]:
import numpy as np

m1 = np.array([[1, 2], [3, 4]])

m2 = np.array([[1, 2], [3, 4]])

print("M1 matrix : \n",m1)

print("M2 matrix : \n",m2)

print("Sum of matrix : \n",m1 + m2)

print("Multiplication of matrix : \n",m1 * m2)

print("Transpose of matrix : \n",m1.transpose())

M1 matrix : 
 [[1 2]
 [3 4]]
M2 matrix : 
 [[1 2]
 [3 4]]
Sum of matrix : 
 [[2 4]
 [6 8]]
Multiplication of matrix : 
 [[ 1  4]
 [ 9 16]]
Transpose of matrix : 
 [[1 3]
 [2 4]]


In [2]:
#Sort Order

my_str = input("Enter a sentence. ")
words = [word.lower() for word in my_str.split()]
#l=my_str.split()
words.sort()
print("Sort in alphabetical order : ",words)

Enter a sentence. Today, is my best day.
Sort in alphabetical order :  ['best', 'day.', 'is', 'my', 'today,']


In [3]:
punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = input("Enter a string: ")
no_punc = ""
for char in my_str:
   if char not in punc:
       no_punc = no_punc + char

print(no_punc)

Enter a string: Please, let us enjoy today!
Please let us enjoy today
