In [9]:
import numpy as n1

#sum of array
arr = n1.arange(0,10)
print("array : ", arr, "\nSum of array : ", n1.sum(arr))


array :  [0 1 2 3 4 5 6 7 8 9] 
Sum of array :  45


In [10]:
#largest element in array
print("array : ", arr, "\nlargest element in array : ", np.amax(arr))

array :  [0 1 2 3 4 5 6 7 8 9] 
largest element in array :  9


In [15]:
# Rotate array
arr1 = np.array([[1,2], [3,4], [5,6]], int)
print("2D array : \n", arr1)
print("Rotate array one type : \n", np.rot90(arr1,2))
print("Rotate array second type : \n", np.rot90(arr1,3))

2D array : 
 [[1 2]
 [3 4]
 [5 6]]
Rotate array one type : 
 [[6 5]
 [4 3]
 [2 1]]
Rotate array second type : 
 [[5 3 1]
 [6 4 2]]


In [52]:
#Split and join array

x = n1.random.randn(3, 3)
x_split = np.split(x, 3, axis=0)
k = 0
print("array : \n", x, "\nsplit array : \n", x_split)
n1.concatenate(x_split[:k] + x_split[k+1:], axis=0)

array : 
 [[-1.05496831  2.04037224 -0.47725821]
 [ 0.70219867  0.09713539  0.04799866]
 [-0.21011762 -1.56276011 -0.42793459]] 
split array : 
 [array([[-1.05496831,  2.04037224, -0.47725821]]), array([[0.70219867, 0.09713539, 0.04799866]]), array([[-0.21011762, -1.56276011, -0.42793459]])]


array([[ 0.70219867,  0.09713539,  0.04799866],
       [-0.21011762, -1.56276011, -0.42793459]])

In [59]:
#monotonicity in array

a = np.asarray([[1,2,3],[1,5,7],[4,3,6]])
print(np.diff(a))
print("Check all difference is greater than 0 : ",  np.all(np.diff(a) > 0) > 0)
np.all(a[:, 1:] >= a[:, :-1], axis=1) # check that each element is greater than the element to its left:
print( "array ",a,"have monotonicity")

[[ 1  1]
 [ 4  2]
 [-1  3]]
Check all difference is greater than 0 :  False
array  [[1 2 3]
 [1 5 7]
 [4 3 6]] have monotonicity
